seed: 2
model: NTF

max_iter: 800000
g_lr: 4e-4
d_lr: 2e-3
ac_lr: 4e-4
adam_betas: [0.0, 0.9]

trainer:
  resume:
  force_resume: False
  work_dir: ./result/NTF
  # Losses
  pixel_loss_type: l1 
  pixel_w: 0.1 
  gan_w: 1.0 
  fm_layers: all 
  fm_w: 0.0 
  # Display
  save: all-last
  print_freq: 1000
  val_freq: 10000
  save_freq: 50000
  tb_freq: 100

dset:
  loader:
    batch_size: 32
    num_workers: 8

  train:
    n_in_s: 3
    n_in_c: 3
